# Generated by Django 3.2.9 on 2022-05-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details_of_incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('PhoneNumber', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('incident', models.CharField(max_length=1000)),
                ('Address', models.CharField(default='null', max_length=500)),
                ('comments', models.TextField(default='null', max_length=1000)),
                ('file', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
